main:
  auto_test: true
  # forza device pytorch ("cpu", "cuda", "mps")
  device: cuda

dqn:
  # alternative: fully_conv_3layer_64ch_11in, global_skip_conv_3layer_64ch_11in 
  architecture_name: fully_conv_3layer_64ch_11in
  # number of hidden convolution channels (called F)
  hidden_channels: 64
  # G size in the global_skip_connection architecture
  global_features_dim: 32
  train:
    agent_seed: 42
    batch_size: 64
    board_height: 9
    board_width: 9
    checkpoint_dir: checkpoints/dqn
    discount_factor: 0.9
    final_epsilon: 0.05
    epsilon_decay_type: exponential # linear, exponential
    epsilon_beta: 0.9995
    learning_rate: 0.00018544040049250931
    learning_starts: 1000
    n_episodes: 50000
    n_mines: 10
    render_mode: null
    replay_buffer_capacity: 100000
    start_epsilon: 1.0
    target_update_frequency: 500
    train_env_seed_start: 50000
    train_frequency: 4
    validation_episodes: 500
    validation_frequency: 100
    validation_seed_start: 500000
    wandb_entity: null
    wandb_project: minesweeper-rl
  test:
    checkpoint_path: checkpoints/dqn/wandb-best/dqn_global-skip-conv_9x9@10_seed45.pt
    board_height: 9
    board_width: 9
    n_mines: 10
    test_seed_start: 1000000
    test_seed_count: 1000
    render_mode: null
    agent_seed: 42
    moving_average_window: 50
    test_output_dir: plots/test
    save_csv: false
    dir_csv: csv/dqn 
    name_csv: null
    log_wandb: false
    wandb_project: minesweeper-rl
    wandb_entity: null

ppo:
  # alternative: fully_conv_3layer_64ch_11in, global_skip_conv_3layer_64ch_11in 
  architecture_name: global_skip_conv_3layer_64ch_11in
  # number of hidden convolution channels (called F)
  hidden_channels: 128
  # G size in the global_skip_connection architecture
  global_features_dim: 32
  # MLP hidden dimension of the critic head
  critic_hidden_size: 512
  train:
    actor_learning_rate: 0.0002329198036719645
    agent_seed: 42
    batch_size: 128
    board_height: 9
    board_width: 9
    checkpoint_dir: checkpoints/ppo
    clip_epsilon: 0.11342242325988612
    critic_learning_rate: 0.0010799480548572082
    discount_factor: 0.95
    entropy_coefficient: 0.001
    gae_lambda: 0.9066208126095492
    max_actor_grad_norm: 1.0
    max_critic_grad_norm: 10.0
    n_episodes: 100000
    n_mines: 25
    render_mode: null
    rollout_steps: 4096
    train_env_seed_start: 50000
    update_epochs: 3
    validation_episodes: 500
    validation_frequency: 5
    validation_seed_start: 500000
    wandb_entity: null
    wandb_project: minesweeper-rl
  test:
    checkpoint_path: checkpoints/ppo/wandb-best/ppo_global-skip-conv_9x9@10_seed43.pt
    board_height: 6
    board_width: 6
    n_mines: 5
    test_seed_start: 1000000
    test_seed_count: 1000
    render_mode: null
    agent_seed: 42
    moving_average_window: 50
    test_output_dir: plots/test
    save_csv: false
    dir_csv: csv/ppo 
    name_csv: null
    log_wandb: false
    wandb_project: minesweeper-rl
    wandb_entity: null

stats:
  csv_a: csv/dqn/dqn_fully-conv_9x9@10_seed43_results.csv
  csv_b: csv/ppo/ppo_fully-conv_9x9@10_seed43_results.csv
  save_path: txt_stats/
  alpha: 0.05

game:
  width: 9
  height: 9
  mines: 10
  seed: null
